### ISSUE TITLE
Ugly output in short terminal windows

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/echelon#4]
Seems there is an issue when terminal window doesn't have too many lines available. Reported from [this Reddit comment](https://www.reddit.com/r/golang/comments/ifo15p/echelon_hierarchical_progress_in_terminals/g2q46xg/?utm_source=reddit&utm_medium=web2x&context=3):

Ah echelon tries to keep the job levels at the top of the currently-visible portion of the console, this is interesting. This only is an issue in case there are too many log lines. This makes the output very ugly though, apart from the last few lines. Just try the demo with passing false to all log.Finish calls.

Example for the issue:

```console
🕒 Job 1 37s
🕒 Job 1 38s
   ❌ Job 4 8.0s
🕒 Job 1 39s
      Doing very important jobs! Completed 25/100...
🕒 Job 1 40s
🕒 Job 1 41s
🕒 Job 1 42s
🕒 Job 1 43s
      Doing very important jobs! Completed 87/100...
🕒 Job 1 44s
      
🕒 Job 1 45s
🕒 Job 1 46s
🕒 Job 1 47s
🕒 Job 1 48s
🕒 Job 1 49s
   ❌ Job 8 9.0s
```

**Comment by fabstu** [comment]
Looks nice! Now the out of scope timers and completion-icons (fail or succeed) won't be updated anymore (MacOS/ZFS). But it is definitely worse when the output gets mangled like before. Thank you 👍

**Comment by fkorotkov** [comment]
Yeah, seems there is no way to edit outside of the terminal window. 😪
