### ISSUE TITLE
Example code for SimpleRenderer

### ISSUE THREAD

**Issue by aric-h** [cirruslabs/echelon#9]
I am relatively new to Go, and am having trouble understanding how to use the SimpleRenderer. Can you please provide some example code?

**Comment by fkorotkov** [comment]
Hey @aric-h, you can check the demo here: https://github.com/cirruslabs/echelon/blob/master/demo/main.go#L14

You'll need to uncomment `renderer := renderers.NewSimpleRenderer(os.Stdout, nil)` and comment out the interractive renderer:

```golang
renderer := renderers.NewInteractiveRenderer(os.Stdout, nil)
go renderer.StartDrawing()
defer renderer.StopDrawing()
```

**Comment by aric-h** [comment]
Thanks. I was able to piece that together after some tinkering around. 
Am I correct in understanding that the SimpleRenderer does not redraw lines of output, but creates new lines instead?

**Comment by fkorotkov** [comment]
Yes, it's useful when you run your tool as part of CI for example and access raw logs afterwards.

**Comment by aric-h** [comment]
Gotchya. Thanks for the clarification!
